### ISSUE TITLE
不適切な表現が見受けられます

### ISSUE THREAD

**Issue by t4t5u0** [DaisenKudo/Docker-Golang-MySQL#8]
https://github.com/DaisenKudo/Docker-Golang-MySQL/blob/fde503537467a6b08e6434e4c3a4b9cbac76355f/golang/src/work/main.go#L59

**Comment by DaisenKudo** [comment]
書いたの @EbichanOO やんけ💢

**Comment by t4t5u0** [comment]
くそわろてる

**Comment by DaisenKudo** [comment]
master修正済み
